# Generated by Django 4.1.7 on 2023-03-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingarea',
            old_name='cars',
            new_name='new_cars'
        ),
    ]
