# Generated by Django 4.1.7 on 2023-03-30 09:01

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingarea',
            name='cars',
        ),
        migrations.AddField(
            model_name='parkingarea',
            name='new_cars',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, to='testapp.car'),
        ),
    ]
